### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by emmaLP** [Ompluscator/gorm-generics#3]
Please can you publish contribution guidelines. I can see some improvements I feel I could help contribute to your code that I have been using for a personal project after some inspiration from your project

**Comment by Ompluscator** [comment]
Hi @emmaLP .

Regarding contribution guidelines, feel free to make any contribution you like, even to add contribution guidelines :)
I am lately too involved at go-live for my company, so I'm willing to give green light for any suggestion you would add, as I do not have too much time to support this repository at this time, unfortunately.
